### ISSUE TITLE
[Feedback] Thankyou!!

### ISSUE THREAD

**Issue by kurokuno** [DaCyclops/ModularChargePacks#1]
have been saying for over a year you should be able to have some kind of chargeable charge on the main power network then go into power armor love it <3

**Comment by DaCyclops** [comment]
I'm glad you like it. There have been a couple of different mods that did a "power from the main network" method. But when I thought about this one, it actually seemed like a fairly unique and different method. 

And as always, it was something created because I was annoyed at something. Because that new Fusion Reactor and its Technology was WAY too costly for me... So charge packs (and the PA1 screenshot is my actual armor from my current game so you can see how I use it...). 

Now if you don't mind, i'm gonna need to close this....
